apiVersion: apps/v1
kind: Deployment
metadata:
  name: reshma164-deploy
  labels:
    app: reshma164-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reshma164-app
  template:
    metadata:
      labels:
        app: reshma164-app
    spec:
      containers:
      - name: reshma164-container
        image: reshma164/sa-wd-webapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reshma164-np-service
  labels:
    app: reshma164-app
spec:
  selector:
    app: reshma164-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
